### ISSUE TITLE
Also your pipelines are now triggered on refs like these: https://github.com/y-kzm/radvd/tree/refs/heads/yykzm-rio-update.. IS that wanted?

### ISSUE THREAD

**Issue by stappersg** [radvd-project/radvd#239]
Also your pipelines are now triggered on refs like these: https://github.com/y-kzm/radvd/tree/refs/heads/yykzm-rio-update.. IS that wanted?

It's a best practice to specify the target branch to trigger github actions on. Eg:
 
```yaml
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*'
   workflow_dispatch:
```

And you can't trigger it manually unless you also add `workflow_dispatch:`

```yaml
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:
```

_Originally posted by @melroy89 in https://github.com/radvd-project/radvd/issues/229#issuecomment-2521206077_
